### ISSUE TITLE
Platform string wrong (Raspberry Pi + Raspbian custom build)

### ISSUE THREAD

**Issue by ThomDietrich** [willemdh/FireMotD#15]
Hey there, I'm bugged by two problems.

1. Platform string wrongly sed'ed:

  ```shell
  dmesg | grep "Rasp"
  [    0.000000] Linux version 4.4.0-1-rpi (debian-kernel@lists.debian.org) (gcc version 4.9.2 (Raspbian 4.9.2-10) ) #1 Debian 4.4.6-1+rpi14 (2016-05-05)
  [    0.000000] Machine model: Raspberry Pi Model B Plus Rev 1.2
  ```
  As you can see, there are two matching lines for `Rasp="$(echo "$Dmesg" | grep "Rasp")"`, producing a malformed Platform string.

2. The Platform string is presented with grep coloring:

  ![2016-08-22 01_13_23-start](https://cloud.githubusercontent.com/assets/2870104/17840373/b0b1960c-6805-11e6-8869-c736d5c60d30.png)
  (after changing to `Rasp="$(echo "$Dmesg" | grep "Rasperry")"`)

**Comment by willemdh** [comment]
Thanks for letting me know. I'll look into it, but it might take a few weeks before I find the time.

**Comment by ThomDietrich** [comment]
I would be interested to get this fixed. Let me create a PR.
Can you tell me (from experience) if changing to `grep "Rasperry"` will be in conflict with some RPi models? I guess not...
