### ISSUE TITLE
Show installation date

### ISSUE THREAD

**Issue by willemdh** [willemdh/FireMotD#24]
Show installation date with command:

`rpm -qi basesystem | grep "Install Date"`

Works only for rpm based os though..

**Comment by ThomDietrich** [comment]
I was curious about the new "Age =", but it's blank on my system. Looking at the latest commit, that's no surprise... If you only retrieve the age for rpm systems, at least show the Age line conditional...!?

**Comment by willemdh** [comment]
That was the plan Thom, but my wife prepared dinner...

**Comment by ThomDietrich** [comment]
Hehe fair enough. I've been digging around a bit but couldn't find a nice solution. Most recommend using tune2fs to get the creation date of the root filesystem, that's however a command only available to root/sudo.

**Comment by willemdh** [comment]
@ThomDietrich Can you test again. Should be clean now.

![image](https://cloud.githubusercontent.com/assets/6462991/21405659/980d9872-c7c7-11e6-8efc-1b86e92e28f2.png)

**Comment by ThomDietrich** [comment]
Yes it's gone again. Thanks ;)

**Comment by willemdh** [comment]
There seems to be another small issue on CentOS 6 systems:

 Installed = Fri 26 Sep 2014 04:28:14 PM CEST      Build Host: c5b2.bsys.dev.centos.org

I'll need to sed some more.. On my to do

**Comment by willemdh** [comment]
Seems all issues with the install date (on CentOS) are fixed. I'm not gonna look into getting this feature for non-rpm systems as I'm not suing those. Closing! :)
