### ISSUE TITLE
Hide FireMotD version number

### ISSUE THREAD

**Issue by ThomDietrich** [willemdh/FireMotD#26]
... or add "FireMotD"

Hey Willem, a few of my users mistake the FireMotD version number as the version number of the overall system. I see the two options above, I would prefer the first but that's of course up to you ;) What do you think?

**Comment by willemdh** [comment]
Hmm. I never had that experience, as 'my users' don't have cli access.

Personally I like the version numbers, as it makes it easy for me. But feel free to make a PR to hide the version with a parameter like -HV|--HideVersion
