### ISSUE TITLE
Shell Checker

### ISSUE THREAD

**Issue by willemdh** [willemdh/FireMotD#27]
Shell Checker is not so happy with some of my commands. I'm planning a major rework, so I'm not getting shellcheck errors.

https://www.shellcheck.net/

@ThomDietrich Could you please test if the apt related changes are not giving any issues (as I'm not using apt)

I still need to verify on SUSE.

**Comment by ThomDietrich** [comment]
Hey @willemdh, I've tested the one change and it's working just as expected. I've pulled the newest revision and everything looks fine.

Btw. just realized that there is an invader theme. You need to add it to the "--help" output.

**Comment by willemdh** [comment]
`$ shellcheck myscript
No issues detected!`

Finally finished the Shellcheck cleanup.

@ThomDietrich @tavinus  @dimon222 Could you guys please check if I missed the ball somewhere as I did many small changes to solve all the shellcheck issues. Tx!!

**Comment by ThomDietrich** [comment]
Great to hear. It's hard to look at the changes across 20 "Spellcheck" commits. Should have squashed these ;) I've pulled the latest revision and everything looks good. One exception:

![grafik](https://cloud.githubusercontent.com/assets/2870104/21751577/9eb0f24a-d5c9-11e6-9a9b-98a666f43434.png)

**Comment by ThomDietrich** [comment]
Found another bug.

![grafik](https://cloud.githubusercontent.com/assets/2870104/21752032/724481c4-d5d1-11e6-91d7-8bd28d919ea1.png)

Solution: Here https://github.com/willemdh/FireMotD/blob/master/FireMotD#L207-L208 the dot is not needed.

```
```

**Comment by willemdh** [comment]
@ThomDietrich Thanks for testing. Did an update, it should be fixed now.

**Comment by ThomDietrich** [comment]
The Platform bug is fixed, thanks!
The alignment bug is now down to 2 missing "#" 😄 May be related to the fact, that my hostname is a bit longer (16 characters)

**Comment by willemdh** [comment]
Thought I created a system one day which calculated the length of the hostname, there will be some bug somewhere, but I'll have no time anymore this week.

**Comment by willemdh** [comment]
I'm closing this up. i'm not really minding the # issue for now (as in fact I'm using the modern theme everywhere) but feel free to make a new isue f it bugs you. Shellchecker is finally no longer reporting any issues. :)
