### ISSUE TITLE
PHP memory_limit parsing

### ISSUE THREAD

**Issue by ThomDietrich** [willemdh/FireMotD#28]
![grafik](https://cloud.githubusercontent.com/assets/2870104/21467183/2be0ff84-c9e5-11e6-9300-c8e7167de616.png)

On my system the memory limit can not be parsed. Reasons:

* php.ini is in a different location
* memory_limit is set to "-1" meaning unlimited

I can add the yet other path and I could translate "-1" to "(unlimited)". Another solution would be hiding of this part. Which would you prefer?

**Comment by dimon222** [comment]
What location do u have for php.ini and is your php part of some package?

**Comment by ThomDietrich** [comment]
`/etc/php5/cli/php.ini` and no, normal package installation

**Comment by dimon222** [comment]
I see, CLI is the one that used by terminal when you call "php" app there, but the one that is referenced in firemotd is actually used by webserver (nginx/Apache/whatever). I believe the webserver's one is supposed to be shown. Check [this](http://askubuntu.com/a/356990/352387).  
  
Are you sure there's no another location for php.ini on your box? "sudo find / -name php.ini"

**Comment by willemdh** [comment]
@ThomDietrich In time it should evolve to a system where the MotD is generated from a configuration file. I'm  still thinking about the best way to achieve this. First thing on my to do is cleaning up the code and making sure Shell Checker has no more complaints, see https://github.com/willemdh/FireMotD/issues/27 

For now I think the easiest workaround might be to hide the memory limit when it's empty.
