### ISSUE TITLE
Camelcase -> lowercase alias

### ISSUE THREAD

**Issue by dimon222** [willemdh/FireMotD#29]
Not sure about the reason of using camelcase instead of lowercase for firemotd. Lowercase - harder to make mistake and easier to type.
Is there some existing application with same name?

**Comment by ThomDietrich** [comment]
Are we talking about the name "FireMotD" or the code style?

**Comment by dimon222** [comment]
Executable name/Alias.

**Comment by willemdh** [comment]
@dimon222 Sorry I made the script camelcase and it will stay like that. Got a whole script library using FireXXX syntax. Would take me months to change all that. :)

 Feel free to make a lowercase alias  though..
