### ISSUE TITLE
Show real memory use (without buffers/cache)

### ISSUE THREAD

**Issue by CyberKiller40** [willemdh/FireMotD#57]
Current: FireMotD shows the whole allocated ram usage, which is not very useful, cause GNU/Linux systems usually allocate close to the whole available ram.

Proposed: show only the really used memory, from the "-/+ buffers/cache:" line of /usr/bin/free

**Comment by willemdh** [comment]
This is probably a good idea. I'll look into it.

**Comment by dimon222** [comment]
Fixed with #68

**Comment by CyberKiller40** [comment]
Thanks!
