### ISSUE TITLE
nginx version shown only when ran as root

### ISSUE THREAD

**Issue by CyberKiller40** [willemdh/FireMotD#58]
Current: on a machine with a running nginx server, using FireMotD as root will show the version of nginx; when ran as a normal user, this information is not shown

If possible please make this info show up when running as a normal user also.

**Comment by dimon222** [comment]
Is nginx symlink up for user that u have? 
If not, then global reference via "nginx -v" obviously will not work.

**Comment by CyberKiller40** [comment]
nginx is in /usr/sbin/nginx which is not on PATH for the normal user, but if called directly then it's executable... So I made a symlink to /usr/bin/nginx and now it's working, thx.
