### ISSUE TITLE
LeftoverChars formula missing from StartGrayTheme

### ISSUE THREAD

**Issue by StormTrooper** [willemdh/FireMotD#70]
This code is missing from the StartGrayTheme function.
```
 LeftoverChars=$((MaxLeftOverChars - HostChars -10))
    (( $LeftoverChars <= 0 )) && LeftoverChars=0
```

Otherwise results in a error:
head: invalid number of bytes: /dev/zero

**Comment by willemdh** [comment]
Ah really sorry I keep forgetting the grey theme in my tests. I'll look into it. Thanks for letting me know.

**Comment by willemdh** [comment]
Should be ok now by .https://github.com/willemdh/FireMotD/pull/74 Let us know if not.
