### ISSUE TITLE
Tree cleanup

### ISSUE THREAD

**Issue by dimon222** [willemdh/FireMotD#71]
Just noticed that I made commit tree ugly compared to early merges.
Can we squash+rebase couple of last commits into respective one-commit-per-PR merge?

![image](https://user-images.githubusercontent.com/2671025/31309118-19a0b192-ab4f-11e7-8874-1dc3842bcb30.png)

**Comment by willemdh** [comment]
Hmm never had to squash rebase. What exactly does it require?

**Comment by dimon222** [comment]
Well, I meant just bunch of fixups and rewordings.

See example of how I would like to make it look:
https://github.com/dimon222/FireMotD/commits/master 
![image](https://user-images.githubusercontent.com/2671025/31309756-68e9c63a-ab59-11e7-89e1-e54a379d3af5.png)

**Comment by willemdh** [comment]
sure go ahead

**Comment by dimon222** [comment]
Its rebase, so unfortunately you might have to unprotect it for a moment, so I can update the tree. Once i'm done, you can protect it back.

**Comment by dimon222** [comment]
Just saw you did it, pushed updated tree, all good.
You can protect it back.

**Comment by willemdh** [comment]
try again now

**Comment by dimon222** [comment]
All good, you can protect it back now.

**Comment by dimon222** [comment]
Can't protect master branch (pls protect it back). Once you done, i'll close this issue.
