### ISSUE TITLE
Issues with usage of free on CentOS 6

### ISSUE THREAD

**Issue by willemdh** [willemdh/FireMotD#75]
@dimon222 @ThomDietrich 

Discovered a new bug with free on CentOS 6. Results is an error message at logon. I'll need to investigate further asap.. 

```
free: invalid option -- '-'
usage: free [-b|-k|-m|-g|-h] [-l] [-o] [-t] [-s delay] [-c count] [-V]
  -b,-k,-m,-g show output in bytes, KB, MB, or GB
  -h human readable output (automatic unit scaling)
  -l show detailed low and high memory statistics
  -o use old format (no -/+buffers/cache line)
  -t display total for RAM + swap
  -s update every [delay] seconds
  -c update [count] times
  -a show available memory if exported by kernel (>80 characters per line)
  -V display version information and exit
```

Version:

```
free -V
procps version 3.2.8
```

**Comment by willemdh** [comment]
Found the problem.

`free --version` does not work on CentOS 6 which uses `procps version 3.2.8`

`free -V` does work and solves the problem for me on both CentOS 6 and 7.

@dimon222 @ThomDietrich 

Can someone asap confirm  `free -V` works on whatever OS you guys are using? Tx

**Comment by dimon222** [comment]
Interesting, never expected such behavior.
free -V perfectly works on my Ubuntu and other Debian based distributives.

**Comment by dimon222** [comment]
Should be fixed by now I assume

**Comment by willemdh** [comment]
@dimon222 yes indeed fixes tx
